### PR TITLE
link to libFLAC/ogg statically for osx

### PR DESCRIPTION
**Pull request by jmarshallnz**
Not sure if this is the best way to be doing this.  ATM we're dynamically linking to flac+ogg, which probably isn't what we want given that these aren't distributed with XBMC any longer, at least if we're going to be distributing the binary add-ons separately.

I take no credit for the .a magic - that's @wsnipex.

@notspiff any comments/suggestions most welcome.  The static linking may well only be appropriate for lesser platforms?

(EDIT: lesser == static)

### CODE REVIEW

**Comment by notspiff** [comment]
why do you have to force lookin for .a? make that the only available?

**Comment by jmarshallnz** [comment]
Yes, forcing for the .a means we needn't go and delete the *.dylib's and/or build the rest of the deps with static-only options.

If the dylibs aren't there, then yes, it'll use the .a's directly and we have no problems.

This came up as for some reason the libFLAC build fails to link if ogg support is enabled and it finds ogg that doesn't have the dylibs available, even though the .a is there.  Haven't looked into exactly why this is - the dylibs were removed after the ogg build, so perhaps redoing the ogg build forcing static libs only will do the trick - will explore.

Obviously for the platforms where we don't want or need to statically link in the deps, we don't want to do this at all, so it definitely needs to be optional at any rate.

Just thought that sometime in the future we may want to have a dep with both static and dynamic libs built, but obviously for add-ons want to link the static only.  Perhaps this is overthinking things though :)

**Comment by jmarshallnz** [comment]
I've confirmed that once ogg/flac are built with `--disable-shared` everything works fine with just the ogg addition (FindOgg.cmake + CMakeLists change).

Happy to go that way if you think that's the better way to go.

**Comment by wsnipex** [comment]
I didn't fully test this on all platforms, but at least on linux setting the ".a" does not harm. It compiles fine, even if no static libs are available.
@jmarshallnz  We could probably also set this globally in xbmc-config.cmake  instead of here, only for darwin if neccessary.

**Comment by notspiff** [comment]
my concern with forcing .a is that you are changing normal behaviour + forcing the issue. shared libraries typically have priority, and i'd be very confused as a third party if this behaved differently.

**Comment by jmarshallnz** [comment]
I'll remove the .a change - the only change needed is the addition of ogg in case the static libFLAC is linked against.

**Comment by notspiff** [comment]
Is there no .pc file for flac?

**Comment by wsnipex** [comment]
you'll have to rename  FindOgg.cmake  to  Findogg.cmake  as well(if its needed)

**Comment by akva2** [comment]
whatever you do, the parameter to the find_package_handle_standard_args() needs to match the casing (i.e. needs to be Foo for FindFoo.cmake)

**Comment by jmarshallnz** [comment]
Updated to fixup the FindOgg.cmake to correct case and drop the change to force static linkage.

Note that my alternate_api branch will likely be the one actually hitting XBMC mainline.

To be honest, I'm not sure whether we should be linking static on OSX/win32 etc.  The alternate I guess is bundling the various dylibs we need into each add-on (there's no need to distribute libFLAC with XBMC after these changes).

**Comment by notspiff** [comment]
linking statically on these platforms makes perfect sense and was always my plan. dynamic offers nothing extra as we they cannot be updated on their own anyways. i checked the .PC for flac, it is broken and do not include the ogg dependency as it should. so sadly this is needed.

**Pull request merged**
